### PR TITLE
#86bz454eq: Fixed use of local API server

### PR DESCRIPTION
**Pull request by dmytrokarimovweticket**

### CODE REVIEW

**Comment by MartianSesame** [comment]
I think we should be rebasing our changes on the latest of gologin

**Comment by MartianSesame** [comment]
Why is this one actually needed?

**Comment by dmytrokarimovweticket** [comment]
> Why is this one actually needed?

we need it to make possible to work locally with gologin-api

**Review by MartianSesame — APPROVED** [review]

**Comment by MartianSesame** [comment]
Task linked: [CU-86bz454eq Cache get browser data](https://app.clickup.com/t/86bz454eq)

**Pull request merged**
